# Generated by Django 4.0.6 on 2022-07-21 09:44

import autoslug.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('image', models.URLField()),
                ('release_date', models.DateField(default=datetime.datetime(2022, 7, 21, 9, 44, 2, 570773, tzinfo=utc))),
                ('lte_exists', models.BooleanField(default=None)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
        ),
    ]
